//Definimos acciones relativas al login
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUSCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';

//Definimos las acciones relativas a los tweets

export const TWEETS_LOADED_REQUEST = 'TWEETS_LOADED_REQUEST';
export const TWEETS_LOADED_SUCCESS = 'TWEETS_LOADED_SUCCESS';
export const TWEETS_LOADED_FAILURE = 'TWEETS_LOADED_FAILURE';

export const TWEET_LOADED_REQUEST = 'TWEET_LOADED_REQUEST';
export const TWEET_LOADED_SUCCESS = 'TWEET_LOADED_SUCCESS';
export const TWEET_LOADED_FAILURE = 'TWEET_LOADED_FAILURE';

export const UI_RESET_ERROR = 'UI_RESET_ERROR';
